workflows:
  flutter-apk:
    name: Food Truck App - Flutter APK
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          cd mobile-app
          flutter packages pub get
      - name: Build APK
        script: |
          cd mobile-app
          flutter build apk --release
    artifacts:
      - mobile-app/build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - build@example.com
        notify:
          success: true
          failure: false 